name: Manual Test

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      # - name: Lint
      #   run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Code coverage
        run: npm run coverage
